FROM splunk/splunk:10.2-rhel9
# Set environment variables for automated setup
ENV SPLUNK_START_ARGS=--accept-license \
    SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com \
    SPLUNK_PASSWORD=changeme \
    SPLUNK_USER=splunk